target 'testNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire' #网络请求框架
pod 'Moya', '~>14.0'
pod 'SwiftyJSON' #Json解析框架
pod 'HandyJSON' #Json解析框架,可转模型
pod 'MJRefresh' #李明杰老师的OC下拉刷新库，可不用桥接直接在swift代码中使用
pod 'SnapKit' #类似Masonry的布局框架
pod 'Kingfisher' #类似SDWebImage的图片加载、缓存框架
pod 'JXSegmentedView'
pod 'JXPagingView/Paging'
  # Pods for News

end